disabled:
  - phpdoc_no_package
  - align_double_arrow
  - concat_without_spaces
  - trailing_comma_in_multiline_array
  - phpdoc_align
  - short_array_syntax
  - phpdoc_separation
  - blank_line_before_return
  - self_accessor
  - single_line_after_imports

enabled:
  - concat_with_spaces
  - no_blank_lines_after_return
  - not_operator_with_successor_space