language: php
dist: trusty
sudo: false

php:
  - 7.4

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml